Repository frlp-utn-ingsoft/shopp, pull requests merged in 2022-05, with the labels that each got.

#1 Agrega modelos
  src/index.js
  src/models/cart.js
  src/models/cartProduct.js
  src/models/index.js
  src/models/product.js
  src/models/productType.js
  tests/unit/models/cart.spec.js
  tests/unit/models/product.spec.js
Labels: enhancement

#2 Feature/home
  package.json
  src/index.js
  src/public/css/style.css
  src/router.js
  src/utils/nunjucks.js
  src/views/_base.html
  src/views/_nav.html
  src/views/home.html
  src/views/templates/_base.html
Labels: enhancement

#4 Agrega obtencion de cantidad de items de un producto
  src/models/cartProduct.js
  tests/unit/models/cartProduct.spec.js
Labels: enhancement

#3 Arregla el borrado de productos en un carrito
  .gitignore
  src/index.js
  src/models/cart.js
  src/models/cartProduct.js
  src/models/index.js
  src/models/product.js
  src/models/productType.js
  src/utils/env.js
  src/utils/nunjucks.js
  tests/unit/models/cart.spec.js
  tests/unit/models/cartProduct.spec.js
Labels: bug

#6 Integracion Continua
  .github/workflows/main.yml
  package-lock.json
  package.json
Labels: enhancement

#7 Metricas y coverage
  .gitignore
  .lighthouserc.js
  README.md
  jest.config.js
  package-lock.json
  package.json
  src/.lhroute.js
  src/index.js
Labels: enhancement

#9 Agrega job de metricas a las actions
  .github/workflows/main.yml
Labels: enhancement

#10 Release/v1.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#12 Feature/discount
  fixtures/products.json
  src/models/product.js
  src/router.js
  src/views/_product-card.html
  src/views/discount.html
  tests/e2e/specs/cart.spec.js
  tests/e2e/specs/dicount.spec.js
  tests/e2e/specs/home.spec.js
  tests/unit/models/product.spec.js
  tests/unit/ui/product-card.spec.js
Labels: enhancement
